### ISSUE TITLE
utelnetserver starts on latest ESP8266 MicroPython, errors on connect

### ISSUE THREAD

**Issue by Hermann-SW** [cpopp/MicroTelnetServer#2]
esp8266-20180904-v1.9.4-491-g5630f277b.bin (elf, map) (latest)

>>> import utelnetserver
>>> utelnetserver.start()
Telnet server started on 192.168.4.1:23
>>> Telnet connection from: ('192.168.4.2', 56126)
Traceback (most recent call last):
  File "utelnetserver.py", line 81, in accept_telnet_connect
OSError: stream operation not supported

**Comment by psy0rz** [comment]
same problem here, with 1.9.4 but on ESP32

**Comment by yoshiyano** [comment]
Hi. I had same problem, too. (1.9.4-494, ESP32)

this is the answer for this problem.
https://forum.micropython.org/viewtopic.php?f=2&t=3298&p=23087&hilit=dupterm#p23087

```
$ diff -u utelnetserver.py.org utelnetserver.py
--- utelnetserver.py.org	2018-10-10 23:33:30.334417591 +0900
+++ utelnetserver.py	2018-10-10 23:34:58.326768231 +0900
@@ -2,12 +2,13 @@
 import network
 import uos
 import errno
+import io
 
 last_client_socket = None
 server_socket = None
 
 # Provide necessary functions for dupterm and replace telnet control characters that come in.
-class TelnetWrapper():
+class TelnetWrapper(io.IOBase):
     def __init__(self, socket):
         self.socket = socket
         self.discard_count = 0
```

**Comment by jdtsmith** [comment]
This fix worked for me with an ESP32 and the newest 1.12 micropython release.  I suggest it be implemented in this codebase!

**Comment by cpopp** [comment]
Merged in a PR that should address this.
